name: "Build and Push"
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branch:
      - main
  issue_comment:
    types:
      - created

jobs:
  fetch-build-option:
    name: "Fetch Build Option"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    outputs:
      build_option: ${{ steps.set-option.outputs.build_option }} # Outputs extracted build option
      option_found: ${{ steps.set-option.outputs.option_found }} # Outputs option found status
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Parse PR Description and Comments for Build Option
        id: parse-comments
        uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request || null;
            const issue = context.payload.issue || pr;

            if (!issue) {
              console.log("No issue or pull request found in the context payload.");
              core.setOutput("build_option", "none");
              core.setOutput("option_found", false);
              return;
            }

            const prNumber = issue.number;
            const repoOwner = context.repo.owner;
            const repoName = context.repo.repo;

            const optionRegex = /\/build-option (all|none|ecs|lambda)/i;

            let buildOption = "none"; // Default build option
            let optionFound = false; // Flag for whether an option is found

            // Check PR body for the build option
            if (pr?.body && optionRegex.test(pr.body)) {
              optionFound = true;
              buildOption = pr.body.match(optionRegex)[1].toLowerCase();
            } else {
              // If not found in the PR body, check comments
              const comments = await github.rest.issues.listComments({
                owner: repoOwner,
                repo: repoName,
                issue_number: prNumber,
              });

              for (const comment of comments.data) {
                const match = comment.body.match(optionRegex);
                if (match) {
                  optionFound = true;
                  buildOption = match[1].toLowerCase();
                  break;
                }
              }
            }

            console.log(`Option Found: ${optionFound}`);
            console.log(`Build Option: ${buildOption}`);

            // Set outputs for later steps
            core.setOutput("build_option", buildOption);
            core.setOutput("option_found", optionFound);
          
      - name: Debug Option Found
        run: |
          echo "Option found: ${{ steps.parse-comments.outputs.option_found }}"

      - name: Set Build Option Output
        id: set-option
        run: |
          echo "build_option=${{ steps.parse-comments.outputs.build_option }}" >> $GITHUB_OUTPUT
          echo "option_found=${{ steps.parse-comments.outputs.option_found }}" >> $GITHUB_OUTPUT

      - name: Post Build Option Required Comment (If Not Found)
        if: ${{ steps.set-option.outputs.option_found == 'false' }}
        uses: actions/github-script@v6
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const repoOwner = context.repo.owner;
            const repoName = context.repo.repo;

            const message = `### Build Option Required 🚀
            Please specify the build option by commenting:
            \`/build-option all|none|ecs|lambda\`

            Example:
            \`/build-option ecs\`

            If no comment is provided, the default build option will be \`none\`.`;

            await github.rest.issues.createComment({
              issue_number: prNumber,
              owner: repoOwner,
              repo: repoName,
              body: message,
            });

  terraform:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'push' }}
    needs: fetch-build-option
    name: "Terraform"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_CLOUD_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: |
          echo "Selected Build Option: ${{ needs.fetch-build-option.outputs.build_option }}"
          terraform plan -no-color -input=false > plan_output.txt
        continue-on-error: true

      - name: Update Pull Request
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const planOutput = require('fs').readFileSync('plan_output.txt', 'utf8');
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`terraform
            ${planOutput}
            \`\`\`

            </details>

            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output,
            });

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false